sudo: required
language: python
python:
  - "pypy"
  - "pypy3"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - git submodule update --init --recursive
install:
  - pip install pylibemu
